pointcloud_from_images:
  ros__parameters:
    depth_topic: stereo/depth
    rgb_topic: camera/rgb
    camera_info_topic: camera/camera_info
    pointcloud_topic: stereo/pointcloud
    sync_queue_size: 10
    sync_slop_sec: 0.05
    publisher_queue_size: 10
    depth_scale: 0.001
    min_depth_m: 0.2
    max_depth_m: 10.0
    pixel_step: 2
    resize_rgb_to_depth: true
    use_color: true
    frame_id: ''
    fx: 0.0
    fy: 0.0
    cx: 0.0
    cy: 0.0