publisch_tf:
  ros__parameters:
    nn_archive: SimpleFruitsYoloV8.rvc2.tar.xz
    resourceBaseFolder: resources
    detections_topic: spatial_detections
    marker_topic: color/ObjectText
    frame_id: oak_rgb_camera_optical_frame
    marker_lifetime_sec: 10.0
